In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import pylab 
import scipy.stats as stats

In [2]:
#LOAD DATA 
df = pd.read_csv('cgpv2000_iter_31.csv', index_col=0)
#DATAFRAME HEAD
df.head()

,nom_ent,mun,nom_mun,loc,nom_loc,longitud,latitud,altitud,pobtot,pmascul,...,vp_lavad,vp_telef,vp_boiler,vp_autom,tothog,hogjefm,hogjeff,pobhog,phogjefm,phogjeff
entidad,,,,,,,,,,,,,,,,,,,,,
31,Yucatán,0,Total de la entidad Yucatán,0,TOTAL DE LA ENTIDAD,NaN,NaN,NaN,1658210,818205,...,193149,105081,74913,86783,387573,319320,68253,1645489,1408724,236765
31,Yucatán,0,Total de la entidad Yucatán,9998,LOCALIDADES DE UNA VIVIENDA,NaN,NaN,NaN,7296,4472,...,136,67,98,132,2051,1988,63,7002,6783,219
31,Yucatán,0,Total de la entidad Yucatán,9999,LOCALIDADES DE DOS VIVIENDAS,NaN,NaN,NaN,2993,1662,...,46,29,51,43,688,647,41,2865,2700,165
31,Yucatán,1,Abalá,0,TOTAL MUNICIPAL,NaN,NaN,NaN,5230,2701,...,222,7,1,27,1244,1112,132,5214,4723,491
31,Yucatán,1,Abalá,1,ABALA,894047.0,203848.0,17.0,1614,824,...,100,1,1,16,387,348,39,1606,1479,127

In [7]:
df.isnull().sum()

nom_ent     0
mun         0
nom_mun     0
loc         0
nom_loc     0
           ..
hogjefm     0
hogjeff     0
pobhog      0
phogjefm    0
phogjeff    0
Length: 131, dtype: int64

In [9]:
df.isna().sum()

nom_ent     0
mun         0
nom_mun     0
loc         0
nom_loc     0
           ..
hogjefm     0
hogjeff     0
pobhog      0
phogjefm    0
phogjeff    0
Length: 131, dtype: int64